name: API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run API Tests for FakeRestApi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle Wrapper
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false
          cache-key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Display Gradle and Java versions
        run: |
          ./gradlew -v
          java -version

      - name: Run Tests
        run: ./gradlew clean test --no-daemon --console=plain --warning-mode=none --quiet
        env:
          LOG_LEVEL: INFO
        continue-on-error: true

      - name: List Allure Results
        if: always()
        run: ls -R build/allure-results || echo "No allure results found"

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Fail if Tests Failed
        if: steps.run_tests.outputs.exit_code != '0'
        run: |
          echo "Gradle tests failed (exit code: ${{ steps.run_tests.outputs.exit_code }})"
          exit 1