name: API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run API Tests and Generate Allure Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # ✅ Use the Gradle Wrapper version (8.10) from your repo, not 9.x on runner
      - name: Setup Gradle Wrapper
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper  # <-- ensures 8.10 from gradle-wrapper.properties
          cache-disabled: false

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Display Gradle and Java versions
        run: |
          ./gradlew -v
          java -version

      - name: Run Tests
        run: ./gradlew clean test --no-daemon --console=plain --warning-mode=none --quiet || true
        env:
          LOG_LEVEL: INFO

      - name: Generate Allure Report
        run: ./gradlew allureReport --no-daemon --console=plain --warning-mode=none --quiet || true

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report
          retention-days: 7

  deploy:
    name: Deploy Allure Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          force_orphan: true

      - name: Add summary with link
        run: |
          echo "Allure Report successfully published!" >> $GITHUB_STEP_SUMMARY
          echo "**Report URL:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
