name: API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Fake Rest Api Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Display Gradle and Java versions
        run: |
          gradle -v
          java -version

      - name: Run Tests (continue on failure, minimal logs)
        run: |
          gradle clean test --console=plain --no-daemon --warning-mode=none --quiet || true
        env:
          LOG_LEVEL: INFO

      - name: Generate Allure Report (even if tests failed)
        if: always()
        run: |
          gradle allureReport --console=plain --no-daemon --warning-mode=none --quiet || true

      - name: Upload Allure Report Artifact (always upload)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report
          retention-days: 7

  deploy:
    name: Deploy Allure Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
          force_orphan: true

      - name: Add summary with link
        run: |
          echo "Allure Report successfully published!" >> $GITHUB_STEP_SUMMARY
          echo "**Report URL:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY
